<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tin Nguyen, Waranya Ratirotjanakul, Amisha Vatsa, Inayat Gill">
<meta name="dcterms.date" content="2026-06-08">

<title>Analysis of Rental Stress Across Australian Regions and Dwelling Types in 2026</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Report_files/libs/clipboard/clipboard.min.js"></script>
<script src="Report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Report_files/libs/quarto-html/popper.min.js"></script>
<script src="Report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Report_files/libs/quarto-html/anchor.min.js"></script>
<link href="Report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Report_files/libs/quarto-html/quarto-syntax-highlighting-7c69b197886ae2a34062761d21e44731.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Report_files/libs/bootstrap/bootstrap-8ffd5f67044e5306d9846f29df41dda5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary">Executive summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a>
  <ul class="collapse">
  <li><a href="#dataset-description" id="toc-dataset-description" class="nav-link" data-scroll-target="#dataset-description">Dataset Description</a></li>
  <li><a href="#dataset-summary" id="toc-dataset-summary" class="nav-link" data-scroll-target="#dataset-summary">Dataset Summary</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#rental-stress-by-dwelling-type" id="toc-rental-stress-by-dwelling-type" class="nav-link" data-scroll-target="#rental-stress-by-dwelling-type">Rental stress by dwelling type</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#recommendations" id="toc-recommendations" class="nav-link" data-scroll-target="#recommendations">Recommendations</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Report.pdf"><i class="bi bi-file-pdf"></i>Typst</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis of Rental Stress Across Australian Regions and Dwelling Types in 2026</h1>
<p class="subtitle lead">ETC5513 – Assignment3</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tin Nguyen, Waranya Ratirotjanakul, Amisha Vatsa, Inayat Gill </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 8, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="executive-summary" class="level1">
<h1>Executive summary</h1>
<p>Australia’s rental market faces significant affordability pressures in 2026, with rising rents outpacing household incomes across most states and dwelling types. This report analyses the <strong>Australian Rental Market Data 2026</strong> dataset <span class="citation" data-cites="kanchana2026">(<a href="#ref-kanchana2026" role="doc-biblioref">Karunarathna 2026</a>)</span>, comprising 6,766 residential rental listings, to examine rental stress using the standard 30% income-to-rent benchmark <span class="citation" data-cites="aihw2025">(<a href="#ref-aihw2025" role="doc-biblioref">Australian Institute of Health and Welfare 2025</a>)</span>. Queensland recorded the highest rental stress rate at 75.1%, while the ACT recorded the lowest at 11.7%, demonstrating that household income is a stronger determinant of affordability than rent levels alone. Across dwelling types, acreage and semi-rural properties were the least affordable (median rent AUD 970/week), while studios remained the most accessible option (median rent AUD 430/week).</p>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Australia’s rental market has faced sustained affordability challenges in recent years, driven by population growth, low vacancy rates, and rising construction costs. These pressures have pushed weekly rents beyond the reach of many low- to middle-income households across both metropolitan and regional areas. Understanding how rental costs vary across states and dwelling types is therefore critical for informing housing policy and supporting renters navigating the current market. This report investigates rental affordability across Australia using the <strong>Australian Rental Market Data 2026</strong> dataset obtained from Kaggle <span class="citation" data-cites="kanchana2026">(<a href="#ref-kanchana2026" role="doc-biblioref">Karunarathna 2026</a>)</span>. The dataset captures weekly rental prices, dwelling characteristics, and geographic attributes for 6,766 residential listings across all states and territories. Rental stress is assessed using the standard 30% income-to-rent benchmark <span class="citation" data-cites="aihw2025">(<a href="#ref-aihw2025" role="doc-biblioref">Australian Institute of Health and Welfare 2025</a>)</span>, applied relative to each state’s median weekly household income. This income-adjusted approach enables more meaningful affordability comparisons across regions with differing cost-of-living profiles. The primary aim of this analysis is to identify where and in what dwelling types rental stress is most acute in Australia in 2026. The Methodology section outlines the dataset and cleaning procedures; the Results section presents key visualisations and findings; and the Discussion, Conclusion and Recommendations section interprets results and offers evidence-based policy directions.</p>
</section>
<section id="methodology" class="level1">
<h1>Methodology</h1>
<p>Before analysis, the dataset was reviewed for missing values, duplicate observations, and variable suitability. One duplicated observation was identified and removed. Missing values occurred only in variables outside the scope of this study and were therefore not treated. Variables unrelated to the research objective, including listing text and detailed address information, were excluded from the analysis. Rental stress was assessed using the standard housing affordability benchmark, where a property was classified as being in rental stress if weekly rent exceeded 30% of the median weekly household income for the corresponding state <span class="citation" data-cites="aihw2025">(<a href="#ref-aihw2025" role="doc-biblioref">Australian Institute of Health and Welfare 2025</a>)</span>.</p>
<section id="dataset-description" class="level2">
<h2 class="anchored" data-anchor-id="dataset-description">Dataset Description</h2>
<p>The cleaned dataset contains 6766 observations and 9 variables. The retained variables include numeric measures describing rental price and dwelling characteristics (<code>price_display</code>, <code>bedrooms</code>, <code>bathrooms</code>, and <code>parking_spaces</code>) and categorical variables describing location and dwelling category (<code>state</code>, <code>locality</code>, <code>suburb</code>, and <code>propertyType</code>). These variables provide the basis for examining rental stress across Australian regions and dwelling types in 2026.</p>
</section>
<section id="dataset-summary" class="level2">
<h2 class="anchored" data-anchor-id="dataset-summary">Dataset Summary</h2>
<p><a href="#tbl-property-summary" class="quarto-xref">Table&nbsp;1</a> summarises the distribution of dwelling types represented in the Australian rental dataset for 2026. Houses accounted for the largest share of observations (4,089 properties; 60.4%), followed by apartments (1,369 properties; 20.2%) and units (761 properties; 11.2%). Together, these dwelling types comprised over 90% of all rental listings, indicating that the dataset primarily reflects conventional residential dwellings.</p>
<div class="cell">
<div id="tbl-property-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-property-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Distribution of rental properties by dwelling type
</figcaption>
<div aria-describedby="tbl-property-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Property type</th>
<th style="text-align: right;">Number of properties</th>
<th style="text-align: right;">Percentage (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">house</td>
<td style="text-align: right;">4089</td>
<td style="text-align: right;">60.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">apartment</td>
<td style="text-align: right;">1369</td>
<td style="text-align: right;">20.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">unit</td>
<td style="text-align: right;">761</td>
<td style="text-align: right;">11.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">townhouse</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">2.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">duplex/semi-detached</td>
<td style="text-align: right;">134</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">studio</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">1.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">flat</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">1.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">other</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">villa</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">0.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">acreage/semi-rural</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">terrace</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In addition to dwelling type composition, <a href="#fig-state-distribution" class="quarto-xref">Figure&nbsp;1</a> shows the distribution of rental properties across Australia in 2026. Most observations were from New South Wales, followed by Victoria and Western Australia, indicating broad geographic coverage of the Australian rental market.</p>
<p>The cleaned dataset and descriptive summaries provide the foundation for evaluating rental stress across Australian regions and dwelling types in 2026.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-state-distribution" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-state-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Report_files/figure-html/fig-state-distribution-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-state-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution of rental properties across Australian states
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>Rental stress is defined here as weekly rent exceeding 30% of the median weekly household income for each state, following the standard affordability benchmark <span class="citation" data-cites="aihw2025">(<a href="#ref-aihw2025" role="doc-biblioref">Australian Institute of Health and Welfare 2025</a>)</span>. Across the full dataset, 59.5% of listings meet this threshold, indicating that the majority of available rentals in 2026 are unaffordable for a median-income household.</p>
<p><a href="#fig-stress-state" class="quarto-xref">Figure&nbsp;2</a> shows the proportion of listings classified as rental stress by state. Queensland recorded the highest stress rate (75.1%), followed by Western Australia (71.6%) and Tasmania (67.3%). Despite having the highest median weekly rent, the Australian Capital Territory had the lowest stress rate (11.7%), reflecting its substantially higher median household income relative to other states. New South Wales, while recording a moderate stress rate of 62.2%, had the largest absolute number of stressed listings (1,678 properties) due to its volume of listings.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-stress-state" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-state-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Report_files/figure-html/fig-stress-state-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-state-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Proportion of rental listings exceeding the 30% income threshold (rental stress) by Australian state, 2026.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="rental-stress-by-dwelling-type" class="level2">
<h2 class="anchored" data-anchor-id="rental-stress-by-dwelling-type">Rental stress by dwelling type</h2>
<p><a href="#tbl-stress-type" class="quarto-xref">Table&nbsp;2</a> summarises the rental stress rate and median weekly rent for each dwelling type. Acreage and semi-rural properties recorded the highest stress rate (88.2%) and the highest median rent ($970/wk), making them the least affordable dwelling category. Houses (65.2%) and apartments (63.1%) followed, representing the most common dwelling types in the dataset. Studios recorded the lowest stress rate (11.5%) and the lowest median rent ($430/wk), making them the most accessible option for renters on median incomes.</p>
<div class="cell">
<div id="tbl-stress-type" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stress-type-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Rental stress rate and median weekly rent by dwelling type.
</figcaption>
<div aria-describedby="tbl-stress-type-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 27%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Property type</th>
<th style="text-align: right;">Number of listings</th>
<th style="text-align: right;">Median rent ($/wk)</th>
<th style="text-align: right;">Stress rate (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">acreage/semi-rural</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">970</td>
<td style="text-align: right;">88.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">terrace</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">750</td>
<td style="text-align: right;">71.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">townhouse</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">700</td>
<td style="text-align: right;">65.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">house</td>
<td style="text-align: right;">4089</td>
<td style="text-align: right;">695</td>
<td style="text-align: right;">65.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">apartment</td>
<td style="text-align: right;">1369</td>
<td style="text-align: right;">700</td>
<td style="text-align: right;">63.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">duplex/semi-detached</td>
<td style="text-align: right;">134</td>
<td style="text-align: right;">650</td>
<td style="text-align: right;">51.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">villa</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">590</td>
<td style="text-align: right;">44.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">unit</td>
<td style="text-align: right;">761</td>
<td style="text-align: right;">550</td>
<td style="text-align: right;">36.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">other</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">540</td>
<td style="text-align: right;">21.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">flat</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">510</td>
<td style="text-align: right;">11.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">studio</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">430</td>
<td style="text-align: right;">11.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>The findings reveal a rental market under considerable strain. With nearly 60% of all listings exceeding the 30% affordability threshold, rental stress reflects a structural mismatch between housing costs and household incomes across most of Australia. Queensland’s stress rate of 75.1% is particularly striking, surpassing even New South Wales despite NSW carrying the largest absolute number of unaffordable listings (1,678 properties). This divergence suggests that stress rates and raw listing volumes tell different stories — Queensland renters face a more acute affordability problem proportionally, while NSW presents the greatest overall scale of housing pressure <span class="citation" data-cites="aihw2025">(<a href="#ref-aihw2025" role="doc-biblioref">Australian Institute of Health and Welfare 2025</a>)</span>.</p>
<p>The ACT stands out as a clear outlier. Despite recording the highest median rent among all states, its stress rate of just 11.7% demonstrates that rent levels alone do not determine affordability — household income plays an equally decisive role. Because the 30% threshold is applied relative to each state’s median weekly income, the ACT’s substantially higher income base shields most renters from stress classification, even at elevated rent levels. This reinforces the importance of income-adjusted affordability measures over simple rent comparisons <span class="citation" data-cites="aihw2025">(<a href="#ref-aihw2025" role="doc-biblioref">Australian Institute of Health and Welfare 2025</a>)</span>.</p>
<p>At the dwelling level, the results reveal a clear affordability gradient. Acreage and semi-rural properties recorded the highest stress rate (88.2%) and the highest median rent ($970/week), making them the least accessible category for median-income renters. Houses (65.2%) and apartments (63.1%) also recorded high stress rates, indicating that affordability pressure is concentrated in the most common dwelling types. Studios recorded the lowest stress rate (11.5%) and the lowest median rent ($430/week), making them the most accessible option in the dataset. As this study is limited to listed rental properties, conclusions about broader supply availability cannot be drawn from these figures alone.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This study examined rental affordability across Australia in 2026 using a dataset of residential listings, applying the standard 30% income-to-rent benchmark to assess rental stress at both the state and dwelling-type level <span class="citation" data-cites="aihw2025">(<a href="#ref-aihw2025" role="doc-biblioref">Australian Institute of Health and Welfare 2025</a>)</span>.</p>
<p>The results paint a sobering picture. Nearly three in five rental listings nationally exceed the affordability threshold, confirming that rental stress is the norm rather than the exception in the current Australian market. At the state level, Queensland, Western Australia, and Tasmania emerged as the most financially pressured regions — not necessarily because their rents are the highest, but because their household incomes are comparatively lower, making even moderate rents unaffordable for median-earning households <span class="citation" data-cites="abs2024">(<a href="#ref-abs2024" role="doc-biblioref">Australian Bureau of Statistics 2024</a>)</span>. The ACT’s low stress rate (11.7%) despite its high median rent reinforces this point clearly: income is the more powerful determinant of affordability than rent price alone.</p>
<p>At the dwelling level, the findings reveal a clear affordability gradient. Acreage and semi-rural properties are the least accessible, with an 88.2% stress rate and a median rent of $970 per week — placing them well beyond reach for most renters. Conventional dwellings such as houses and apartments, which make up the bulk of the market, also recorded high stress rates (65.2% and 63.1% respectively), suggesting that even mainstream housing options are increasingly unaffordable. Studios stand out as the most accessible dwelling type, with a stress rate of just 11.5% and a median rent of $430 per week, though their small share of total listings limits their impact as a broad solution.</p>
<p>Taken together, these findings indicate that rental unaffordability in Australia in 2026 is both widespread and structurally entrenched, varying meaningfully by both geography and dwelling type.</p>
</section>
<section id="recommendations" class="level1">
<h1>Recommendations</h1>
<p>Based on these findings, several policy directions warrant consideration.</p>
<p>First, state governments in Queensland, Western Australia, and Tasmania should be prioritised for targeted rental relief measures. Given that stress in these states is driven largely by the income–rent gap rather than extreme rent levels alone, income-side interventions — such as expanded Commonwealth Rent Assistance payments calibrated to state-level median incomes — are likely to be more effective than rent caps applied uniformly at the national level <span class="citation" data-cites="grattan2023">(<a href="#ref-grattan2023" role="doc-biblioref">Grattan Institute 2023</a>)</span>.</p>
<p>Second, increasing the supply of smaller, more affordable dwelling types — particularly studios and one-bedroom apartments — should be a planning priority in high-stress states. The data clearly show studios offer the most accessible entry point into the rental market, yet they represent a small fraction of total listings. Rezoning and density incentives in well-connected urban areas could help grow this segment of supply <span class="citation" data-cites="reia2024">(<a href="#ref-reia2024" role="doc-biblioref">Real Estate Institute of Australia 2024</a>)</span>.</p>
<p>Third, the affordability crisis in conventional housing categories (houses and apartments) demands attention given their dominance in the dataset. Policy levers such as build-to-rent schemes, social housing investment, and inclusionary zoning requirements for new developments could help moderate stress rates in these high-volume categories over the medium term <span class="citation" data-cites="grattan2023">(<a href="#ref-grattan2023" role="doc-biblioref">Grattan Institute 2023</a>)</span>.</p>
<p>Finally, this study highlights the limitations of applying a single national income benchmark to assess rental stress. Future research should incorporate suburb-level or postcode-level income data — available through the ABS — to produce more granular affordability assessments <span class="citation" data-cites="abs2024">(<a href="#ref-abs2024" role="doc-biblioref">Australian Bureau of Statistics 2024</a>)</span>. Integrating vacancy rates, rental growth trends, and household composition data would further strengthen the analytical basis for evidence-based housing policy in Australia.</p>
</section>
<section id="bibliography" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-abs2024" class="csl-entry" role="listitem">
Australian Bureau of Statistics. 2024. <em>Housing Occupancy and Costs</em>. <a href="https://www.abs.gov.au/statistics/people/housing/housing-occupancy-and-costs">https://www.abs.gov.au/statistics/people/housing/housing-occupancy-and-costs</a>.
</div>
<div id="ref-aihw2025" class="csl-entry" role="listitem">
Australian Institute of Health and Welfare. 2025. <em>Housing Assistance in Australia: Financial Assistance</em>. <a href="https://www.aihw.gov.au/reports/housing-assistance/housing-assistance-in-australia/contents/financial-assistance">https://www.aihw.gov.au/reports/housing-assistance/housing-assistance-in-australia/contents/financial-assistance</a>.
</div>
<div id="ref-grattan2023" class="csl-entry" role="listitem">
Grattan Institute. 2023. <em>Rental Stress and Housing Policy in Australia</em>. <a href="https://grattan.edu.au">https://grattan.edu.au</a>.
</div>
<div id="ref-kanchana2026" class="csl-entry" role="listitem">
Karunarathna, Kanchana. 2026. <em>Australian Rental Market Data 2026</em>. Kaggle. <a href="https://www.kaggle.com/ds/9582256">https://www.kaggle.com/ds/9582256</a>.
</div>
<div id="ref-reia2024" class="csl-entry" role="listitem">
Real Estate Institute of Australia. 2024. <em>Housing Affordability Report</em>. <a href="https://www.reia.com.au">https://www.reia.com.au</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="Report_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>